<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>comment</key>
	<string>node.js</string>
	<key>foldingStartMarker</key>
	<string>(^.*{[^}]*$|^.*\([^\)]*$|^.*/\*(?!.*\*/).*$)</string>
	<key>foldingStopMarker</key>
	<string>(^\s*\}|^\s*\)|^(?!.*/\*).*\*/)</string>
	<key>keyEquivalent</key>
	<string>^~N</string>
	<key>name</key>
	<string>JavaScript Node</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\b(exports)\b</string>
			<key>name</key>
			<string>variable.language.module.js</string>
		</dict>
		<dict>
			<key>include</key>
			<string>source.js</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.js.node</string>
	<key>uuid</key>
	<string>17076F45-FE22-4123-AD00-0C8E31BC2EB8</string>
</dict>
</plist>
